### ISSUE TITLE
the  custom attributes mcv_rightArrowMask and mcv_leftArrowMask don't work

### ISSUE THREAD

**Issue by Hiderrrrrr** [prolificinteractive/material-calendarview#380] opened 2016-07-29 09:39 UTC
when i use this widget i find out that two custom attributes don't work .
mcv_rightArrowMask and mcv_leftArrowMask.
i read the code and found out where went wrong.
`Drawable leftMask = a.getDrawable(
                    R.styleable.MaterialCalendarView_mcv_leftArrowMask
            );
            if (leftMask == null) {
                leftMask = getResources().getDrawable(R.drawable.mcv_action_previous);
            }
            setLeftArrowMask(leftMask);
            Drawable rightMask = a.getDrawable(
                    R.styleable.MaterialCalendarView_mcv_rightArrowMask
            );
            if (rightMask == null) {
                rightMask = getResources().getDrawable(R.drawable.mcv_action_next);
            }
            setRightArrowMask(rightMask);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            a.recycle();
        }adapter.setTitleFormatter(DEFAULT_TITLE_FORMATTER);
        setupChildren();`

the method setupChild() goes after the method setRightArrowMask()
that's what makes the attribute don't work
the method setRightArrowMask() do what the attribute want,but then the method setupChildren() make the button back to original state.

**Comment by quentin41500** [comment] 2016-09-26 15:07
I think this is a duplicate of #375

**Comment by quentin41500** [comment] 2016-10-10 20:19
Fixed in v1.4.2

**Closed by quentin41500** 2016-10-10 20:19 UTC
Labels: duplicate
