### ISSUE TITLE
Allow changing the default number of weeks

### ISSUE THREAD

**Issue by ivandeskov** [prolificinteractive/material-calendarview#358] opened 2016-06-22 15:48 UTC
Hi chaps,
I can't find a way of changing the number of weeks when in month view and 'other_months' flag on. Currently six weeks are displayed and some might consider five to be enough. Are you willing to agree with such an option?
Thanks

**Comment by quentin41500** [comment] 2016-06-22 16:07
@ivandeskov this is a duplicate of #351. I let you read the thread and ask if you have further questions there. Closing this issue for now. Feel free to reopen if you are not asking the same thing.

**Closed by quentin41500** 2016-06-22 16:07 UTC
