### ISSUE TITLE
CalendarDay.today().toString showing wrong date

### ISSUE THREAD

**Issue by richardrun** [prolificinteractive/material-calendarview#590] opened 2017-05-30 06:16 UTC
It's May this month, but it is showing CalendarDay{2017-4-29}.
Should be easy fix

**Comment by quentin41500** [comment] 2018-06-22 16:07
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/459.

**Closed by quentin41500** 2018-06-22 16:07 UTC
