### ISSUE TITLE
Change from MonthlyView to WeeklyView

### ISSUE THREAD

**Issue by varunkumarj** [prolificinteractive/material-calendarview#765] opened 2018-05-17 08:55 UTC
How to Change from MonthlyView to WeeklyView using a smooth Animation ? Please Help

**Comment by quentin41500** [comment] 2018-05-17 14:29
https://github.com/prolificinteractive/material-calendarview/issues/341

**Comment by quentin41500** [comment] 2018-06-26 17:57
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/341

**Closed** 2018-06-26 17:57 UTC
Labels: duplicate
