### ISSUE TITLE
Support for API 11 , it seems support is from 14 .

### ISSUE THREAD

**Issue by pradhucodes** [prolificinteractive/material-calendarview#123] opened 2015-09-13 05:52 UTC
This is not a bug just confirming if you can update it to 11 . Is there some functionality which requires min 14.

**Comment by dandc87** [comment] 2015-09-14 15:50
This is a duplicate of #96. There shouldn't be much functionality blocking this. A PR would be welcome.

**Closed by dandc87** 2015-09-14 15:50 UTC
