### ISSUE TITLE
Selection not working any more on lollipop after month swipe 

### ISSUE THREAD

**Issue by Ashish19901** [prolificinteractive/material-calendarview#768] opened 2018-05-23 06:31 UTC
i am using current latest version 1.4.3

 compile 'com.prolificinteractive:material-calendarview:1.4.3'

when i check in lollipop version after one month swipe date selected color not change

 <com.prolificinteractive.materialcalendarview.MaterialCalendarView
                android:id="@+id/calendarView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="5dp"
                android:background="@android:color/white"
                app:mcv_arrowColor="@color/black"
                app:mcv_calendarMode="month"
                app:mcv_selectionColor="#7FCD00"
                app:mcv_showOtherDates="all"/>

- selection color not change

**Comment by quentin41500** [comment] 2018-07-11 17:17
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/740

**Comment by quentin41500** [comment] 2018-07-11 17:18
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/100

**Closed by quentin41500** 2018-07-11 17:17 UTC
