### ISSUE TITLE
add long click event on a certain day

### ISSUE THREAD

**Issue by ignivajigyasa** [prolificinteractive/material-calendarview#751] opened 2018-04-09 07:01 UTC
Unable to add long click or touch listener on a particular day.

**Comment by Marchuck** [comment] 2018-04-20 15:48
my fork can do this using OnDatePickedListener
https://github.com/Marchuck/material-calendarview

see branch feature/on-date-picked-listener

**Comment by quentin41500** [comment] 2018-06-22 16:47
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/335. Closing

**Closed by quentin41500** 2018-06-22 16:47 UTC
Labels: enhancement
