### ISSUE TITLE
CalendarDay.from(int year, int month, int day) issue in month

### ISSUE THREAD

**Issue by 0wzZZzz6** [prolificinteractive/material-calendarview#454] opened 2016-10-25 03:25 UTC
CalendarDay day = CalendarDay.from(2016, 9, 29);

I was expecting that it will result into September 29, 2016.
but why is that it results to October 29, 2016.

**Comment by androchentw** [comment] 2016-11-24 10:00
duplicate with #459, the index of Month of [java.util.Calendar] starts from 0

so when you code 

```java
CalendarDay.from(2016, 9, 29);
``` 

it actually means 

```java
CalendarDay.from(2016, Calendar.OCTOBER, 14);
```

[java.util.Calendar]: https://developer.android.com/reference/java/util/Calendar.html

**Comment by quentin41500** [comment] 2018-06-22 16:07
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/459.

**Closed by quentin41500** 2018-06-22 16:07 UTC
