### ISSUE TITLE
Is possible to change months background color?

### ISSUE THREAD

**Issue by nAkhmedov** [prolificinteractive/material-calendarview#354] opened 2016-06-18 07:40 UTC
How can i change Header side background color? I want to set multiple color to calendar, for example weekday and date sides are red, top side(header) is white. is it possible to impelement like this
default
![default](https://cloud.githubusercontent.com/assets/8067423/16169718/c425271c-3551-11e6-8bc8-096fe67d98b7.png)

**Comment by quentin41500** [comment] 2016-06-21 14:39
@nAkhmedov Take a look at https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#custom-labels and the text appearance section right below. 

You might found some examples in the sample app.

**Comment by quentin41500** [comment] 2016-06-22 18:18
Closing this issue for now, reopen if you have any more questions

**Closed by quentin41500** 2016-06-22 18:18 UTC

**Comment by agramian** [comment] 2016-10-23 08:53
I'm trying to achieve the same thing as @nAkhmedov and having trouble when setting a custom tile height.

What I've tried so far was to add a decorator to the calendar widget which sets the background for every day in the month to a certain color.  The problem is there seems to be some padding or margin on each of the tiles so that the background is not seamless (see attached image).

If I don't set the custom tile height then the background is seamless.  Is there a way to achieve a seamless background color for the months when setting a custom tile height?  I tried setting the `android:background` attribute for `mcv_dateTextAppearance` through xml instead of the decorator but that did not do anything.

![screen shot 2016-10-23 at 1 47 05 am](https://cloud.githubusercontent.com/assets/7113257/19625060/fc265a94-98c2-11e6-8876-1a82acf7a8c5.png)

**Comment by agramian** [comment] 2016-10-24 07:19
UPDATE:

If I use `view.setSelectionDrawable()` instead of `view.setBackgroundDrawable()` the background color will be seamless (so now it's unclear to me what the purpose of `setBackgroundDrawable()` is at all for the decorators).

Unfortunately there is still a problem even when using `setSelectionDrawable()` as the selection drawable will be stretched when using a `ShapeDrawable`.  If a `BitmapDrawable` is used with the `android:gravity="center"` attribute then it will not stretch.  However I don't want to make a bitmap just to hold a colored circle because I'd like to be able to easily adjust the color instead of having to create new assets each time.

I think the problem is in `DayView.java` in the `generateCircleDrawable()` method.  This should set the width and height to be a perfect circle.  If the dimensions are not explicitly set it probably just adopts the parent's size.

```
    private static Drawable generateCircleDrawable(final int color) {
        ShapeDrawable drawable = new ShapeDrawable(new OvalShape());
        drawable.getPaint().setColor(color);
        return drawable;
    }
```

Really there should just be a way to set the background color without having to redefine the selector for choosing the dates.

![screen shot 2016-10-24 at 12 18 06 am](https://cloud.githubusercontent.com/assets/7113257/19636646/64d94814-997f-11e6-8b6e-846123505851.png)
