### ISSUE TITLE
Date on selected returns invalid month

### ISSUE THREAD

**Issue by sathya329** [prolificinteractive/material-calendarview#710] opened 2017-12-17 05:22 UTC
The date selected was Decemeber 11 2017 but ondate listener returns 11-11-2017.How to resolve this issue.On changing the calendar mode from months to week on swipe how to set the date selected from the previous week's selected date.

Finally thanks for this amazing library..

**Comment by tjouin** [comment] 2017-12-21 10:26
I think it not a bug, For CalendarDay December is 11 and January is 0 !

**Comment by quentin41500** [comment] 2018-06-22 16:07
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/459.

**Closed by quentin41500** 2018-06-22 16:07 UTC
