### ISSUE TITLE
View Draw issue

### ISSUE THREAD

**Issue by flamenvo** [prolificinteractive/material-calendarview#102] opened 2015-08-13 09:48 UTC
@dandc87       How can I solve this problem
![360 0813_15_41_01](https://cloud.githubusercontent.com/assets/2337535/9247070/f93a073c-41e2-11e5-9ad1-56e488ff99e7.png)

**Comment by dandc87** [comment] 2015-08-13 15:52
Hi @flamenvo, are you referring to the left and right months being drawn? This is being fixed in pull request #99 and the issue is being tracked with #84.

**Comment by dandc87** [comment] 2015-08-21 22:47
Assuming that this is the same issue as #84, which is now fixed.

**Closed by dandc87** 2015-08-21 22:47 UTC
