### ISSUE TITLE
DayViewDecorator setSelectionDrawable oval shape in android 5.1.1 and 6.0.1

### ISSUE THREAD

**Issue by Nathiya-Smitiv** [prolificinteractive/material-calendarview#739] opened 2018-02-26 07:06 UTC
MaterialCalendarView widget;

 widget.setTileSize(-1);
        widget.setTileWidthDp(LinearLayout.LayoutParams.MATCH_PARENT);
        widget.setTileHeightDp(38);
        widget.addDecorator(new MySelectorDecorator(getActivity()));

public class MySelectorDecorator implements DayViewDecorator {
        private final Drawable drawable;
        public MySelectorDecorator(Activity context) {
            drawable = context.getResources().getDrawable(R.drawable.my_selector_default);
        }
        @Override
        public boolean shouldDecorate(CalendarDay day) {
            return true;
        }
        @Override
        public void decorate(DayViewFacade view) {
            view.setSelectionDrawable(drawable);
        }
    }

<selector xmlns:android="http://schemas.android.com/apk/res/android"
    android:exitFadeDuration="@android:integer/config_shortAnimTime">

    <item android:state_checked="true"
        android:drawable="@drawable/ic_my_selector" />
    <item android:state_pressed="true"
        android:drawable="@drawable/ic_my_selector" />
 <item android:drawable="@android:color/transparent" />

</selector>

EventDecorator setBackgroundDrawable is working fine in android lollipop and marshmallow but 
DayViewDecorator setSelectionDrawable is displays with oval shape like below
Android 5.1.1 with default selector icon and my circle icon also shows in oval shape.
![cal1](https://user-images.githubusercontent.com/33314429/36657147-7f82ac92-1af1-11e8-8fbf-8c0fe43ec2f4.png)
![cal2](https://user-images.githubusercontent.com/33314429/36657161-8b019b3c-1af1-11e8-864d-22e673bd0e7a.png)
Android 6.0.1 screenshot.
![cal3](https://user-images.githubusercontent.com/33314429/36657210-b01e8c4a-1af1-11e8-8bf4-7f455b869216.png)
Kindly help me to solve the design issue. I am using the Latest Version 1.4.3

**Comment by quentin41500** [comment] 2018-07-25 19:13
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/556

**Closed by quentin41500** 2018-07-25 19:13 UTC
