### ISSUE TITLE
Add Custom Day Views

### ISSUE THREAD

**Issue by o2themar** [prolificinteractive/material-calendarview#372] opened 2016-07-21 00:48 UTC
So right now when you add a decorator to a day view it applies whatever you set in the decorate method to all days that are matched by shouldDecorate. It would be great if we would be able to pass data to each day to display for example some word/number as a subscript or superscript to the day number. This should be customizable to allow adding data all around the day number. This data is a quick summary and shouldn't be too long.

**Comment by quentin41500** [comment] 2018-06-22 22:21
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/313

**Closed by quentin41500** 2018-06-22 22:21 UTC
Labels: enhancement
