### ISSUE TITLE
ClassCastException - WeekView to MonthView

### ISSUE THREAD

**Issue by kostaniakm** [prolificinteractive/material-calendarview#285] opened 2016-05-09 14:38 UTC
I am using this calendar inside row on RecyclerView. I am setting calendar's display mode to CalendarMode.WEEKS. This row is on top of list. 

I scroll down the list and then on the top of the list, then there is class cast exception. 

I am using view holder pattern. Imo this is viewholder fault.

```
java.lang.ClassCastException: com.prolificinteractive.materialcalendarview.WeekView cannot be cast to com.prolificinteractive.materialcalendarview.MonthView
                                                                                at com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.getItemPosition(CalendarPagerAdapter.java:125)
                                                                                at com.prolificinteractive.materialcalendarview.WeekPagerAdapter.getItemPosition(WeekPagerAdapter.java:9) 
```

Any solutions?

**Comment by ekchang** [comment] 2016-05-10 00:57
Can you include a pastebin/gist of how your adapter and layouts are set up? `MonthView` and `WeekView` are separate subclasses of `CalendarPagerView`.

But I have a hunch it is because RV recreates the MCV and by default it is using month mode, forcing you to call `setCalendarMode(WEEKS)` during `onBind`. I don't think this should crash, but it might be crashing if you are only calling `setCalendarMode(WEEKS)` during `onCreateVH`.

There's a potential enhancement here: add an attribute to set week/month mode in XML. I'll create an issue request and reference.

**Comment by kostaniakm** [comment] 2016-05-10 11:54
Im using my own ```typedViewHolderAdapter```. 
way to create it:
```
    private TypedViewHolderAdapter<BaseCinemaItem> createAdapter() {
        return new TypedViewHolderAdapter.Builder<BaseCinemaItem>()
                .addFactory(CinemaCalendarViewHolder.factory(this))
                .addFactory(ListErrorViewHolder.factory())
                .addFactory(MovieViewHolder.factory(this))
                .addFactory(MovieWithHoursViewHolder.factory(this))
                .build();
    }
```
Below source codes:
ViewHolder:
https://gist.github.com/kostaniakm/4c21c705539fcd57534e0fdc2b621dab
xml. layout:
https://gist.github.com/kostaniakm/3f09c04a53293841440a4e2f6dab4684

Im setting Calendar mode during ```onBind```. According to me what you suspect is the cause of the crash.

**Comment by kostaniakm** [comment] 2016-05-11 00:17
I checked version from ```future-1.x``` branch and this is not solving my problem. Same exception.

**Comment by ekchang** [comment] 2016-05-11 00:19
Are you setting`mcv_calendarMode="week"` in your layout?

**Comment by kostaniakm** [comment] 2016-05-11 00:19
Yes, I am.

**Comment by ekchang** [comment] 2016-05-11 00:21
I'll try to reproduce the issue in a sample app or (if you already have one) feel free to upload to github/bitbucket and link me to it.

**Comment by ekchang** [comment] 2016-05-11 00:41
Please check out the example on my fork, specifically RecyclerViewActivity: https://github.com/ekchang/material-calendarview/tree/ec/rv_example

There I create 10 calendars as items (set to Week, via XML) with no problems while scrolling through. This doesn't seem to be an issue with MCV, perhaps you are casting when you don't need to during `onBind`? And make sure you are not using `MonthView/MonthViewPager` if you are only dealing with Weeks.

**Comment by kostaniakm** [comment] 2016-05-11 01:12
Okay, I hope you got the right one! I'm gonna check also your sample or do mine but later, it is very late at night right now (3 am now).

**Comment by ekchang** [comment] 2016-05-11 01:32
I will push a hotfix (for now) which will stop the crash but there is a deeper problem where I believe `CalendarPagerAdapter#getItemPosition` is giving the wrong value for Week mode (due to the internal way the position used to be calculated with months. I will close this when the crash issue is fixed and log a separate bug for wrong position.

**Comment by kostaniakm** [comment] 2016-05-11 01:59
That hotfix (I was talking about it from beggining) fixes crash problem but I also see the new problem right now. We need new way to calculate ```minDate``` for WeekMode. Thanks for help, I'll try to find solution too.

**Comment by ekchang** [comment] 2016-05-11 02:04
Yep, I'm aware that it's a problem and logged it as a separate bug in #292. If you find the solution, feel free to shoot over a PR. Closing this as the crash has been resolved.

**Closed by ekchang** 2016-05-11 02:04 UTC
Labels: bug

**Comment by quentin41500** [comment] 2016-05-11 19:58
Seems like the issue is coming from `materialCalendarView#setFirstDayOfWeek(Calendar.WEDNESDAY);`
