### ISSUE TITLE
Date becomes out of sync in OnMonthChanged listener

### ISSUE THREAD

**Issue by velleic** [prolificinteractive/material-calendarview#346] opened 2016-06-14 10:45 UTC
When setting dates based on the date reported from OnMonthChanged I noticed something rather odd.
The GregorianCalendar within CalendarDay can become out of sync.

What I did to create this:
I paged in one direction, then paged in the other direction (back to the initial page). Looking at the debugger, I could see that the MONTH of the GregorianCalendar was one higher than it should be.
So, paging to May from June, I get GregorianCalendar MONTH = 4 and CalendarDay month = 4, as it should be. 
Paging back to June, GregorianCalendar MONTH = 6 and CalendarDay month = 5, which is incorrect. Paging on to July gives 6 and 6, as it should.

This can happen in the other direction as well, and the dates can become even more out of sync. 
The "current date" in the GregorianCalendar seems to end up 1 higher than when I began paging left. Both Date and CalendarDay remain correct.

**Comment by quentin41500** [comment] 2016-06-22 18:40
@velleic Im not able to reproduce, can you tell me exactly what you are printing from the `onMonthChanged` listener? 

Printing this:
```java    
@Override
public void onMonthChanged(MaterialCalendarView widget, CalendarDay date) {
    Log.e("BasicActivity", "CalendarDay: " + date.getMonth() + " - Greg: " + date.getCalendar().get(Calendar.MONTH));
}
```
I get this:
```
BasicActivity: CalendarDay: 4 - Greg: 4
BasicActivity: CalendarDay: 5 - Greg: 5
BasicActivity: CalendarDay: 6 - Greg: 6
```

**Comment by velleic** [comment] 2016-06-23 08:26
I think I've figured it out.
The actual problem was that I took that Calendar from CalendarDay and used it elsewhere in my code, where I did things like setting the day of the month to the last day. Anyway, I used the Calendar instance straight from the CalendarDay, and then the changes I made to the Calendar seemed to persist onto the "new" Calendar when I changed the month.

The Javadocs say getCalendar is

> a new calendar instance with this day information

but it seems like it's not a new instance?

**Comment by quentin41500** [comment] 2016-06-23 15:18
You can look at the code: 
```java
public Calendar getCalendar() {
        if (_calendar == null) {
            _calendar = CalendarUtils.getInstance();
            copyTo(_calendar);
        }
        return _calendar;
    }

public void copyTo(@NonNull Calendar calendar) {
        calendar.clear();
        calendar.set(year, month, day);
    }
```
Calendar is set to the date of CalendarDay and that's it. If you want to instantiate a new Calendar yourself, use `CalendarUtils.getInstance()`.

Closing this issue now, let me know if you have any further questions

**Closed by quentin41500** 2016-06-23 15:18 UTC

**Comment by cyberformed** [comment] 2018-04-25 10:57
Dude, not working at all.
Unable to catch the next and prev months using this code. Any other ways to do this.
