### ISSUE TITLE
No background when clicked the day

### ISSUE THREAD

**Issue by HousTracy** [prolificinteractive/material-calendarview#396] opened 2016-08-31 04:14 UTC
When slide to next month or last month ,when clicked the day ,there is no circle background showed.
The mode is range

**Comment by quentin41500** [comment] 2016-09-26 14:46
Hey @HousTracy, I sadly can't reproduce your issue! Could you provide more information? Maybe some code, screenshots, a video or steps to reproduce? Are you able to reproduce this bug with the sample app as well?

Thank you in advance

**Comment by HousTracy** [comment] 2016-10-25 07:33
@quentin41500 Sorry,busy for a period of time.I'll give you some steps detailly.
1.Set the mode,we are MaterialCalendarView.SELECTION_MODE_RANGE,and show the current month(now is Oct)
2.select start day and end at random (now everything is OK)
3.slide to the next month or last month ,repeat the step 2,we will see the circle background doesn't show immediately at the range of selected days.
![step_three](https://cloud.githubusercontent.com/assets/9032088/19676609/e66f244a-9ac7-11e6-95c2-53750868a924.png)
![step_two](https://cloud.githubusercontent.com/assets/9032088/19676610/e945e5aa-9ac7-11e6-9830-2ea951ba94fc.png)

**Comment by quentin41500** [comment] 2018-07-11 16:56
I still couldn't reproduce with 1.6.0, closing.

**Closed by quentin41500** 2018-07-11 16:56 UTC
Labels: bug
