### ISSUE TITLE
in sample BasicActivityDecorated Some mistake

### ISSUE THREAD

**Issue by yanwencheng** [prolificinteractive/material-calendarview#468] opened 2016-11-15 03:49 UTC
When I set dates parameter value“2016-11-14”,But in the control of the "2016-12-14" display Span.Code as follows
`   Calendar calendar = Calendar.getInstance();
            calendar.add(Calendar.MONTH, 3);
            ArrayList<CalendarDay> dates = new ArrayList<>();
            CalendarDay day = CalendarDay.from(2016,11,14);
            dates.add(day);
            return dates;`

**Comment by androchentw** [comment] 2016-11-24 09:44
duplcate with #459, the index of Month of [java.util.Calendar] starts from 0

so when you code 

```java
CalendarDay.from(2016,11,14);
``` 

it actually means 

```java
CalendarDay.from(2016, Calendar.DECEMBER, 14);
```

[java.util.Calendar]: https://developer.android.com/reference/java/util/Calendar.html

**Comment by yanwencheng** [comment] 2016-12-04 10:57
@androchentw thank you

**Comment by quentin41500** [comment] 2018-06-22 16:07
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/459.

**Closed by quentin41500** 2018-06-22 16:07 UTC
