### ISSUE TITLE
(RESOLVED) App Crashing Run time XML error 

### ISSUE THREAD

**Issue by KhanStan99** [prolificinteractive/material-calendarview#733] opened 2018-02-12 10:45 UTC
RESOLVED!
I added "next" string in my string.xml file and then i renamed it to string_next, so material-celendarview was not able to read it. Resolved by chaging string_next to next....

This crash is happening from last 2 days. I havent changed anything in my project and other external dependencies are working fine. but material-calendarview gives me this run time error.

Here is my error log:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.scoratech.scoraxchange, PID: 30847
                                                                            android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.prolificinteractive.materialcalendarview.MaterialCalendarView
                                                                            Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.prolificinteractive.materialcalendarview.MaterialCalendarView
                                                                            Caused by: java.lang.reflect.InvocationTargetException

My XML Code:
 `    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
                    android:id="@+id/myEventsCalendar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_marginEnd="@dimen/marginThirty"
                    android:layout_marginStart="@dimen/marginThirty"
                    app:mcv_selectionColor="@color/colorPrimary" />

                <com.prolificinteractive.materialcalendarview.MaterialCalendarView
                    android:id="@+id/deptEventsCalendar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_marginEnd="@dimen/marginThirty"
                    android:layout_marginStart="@dimen/marginThirty"
                    android:visibility="gone"
                    app:mcv_selectionColor="@color/colorPrimary" />
`

Here is Android Studio preview...
![image](https://user-images.githubusercontent.com/25157365/36093342-5c6dca3e-1010-11e8-9f40-859621bf70d3.png)

Please let me know what causing this problem', Thanks

**Comment by sirajsumra** [comment] 2018-04-09 13:37
Hi,

How do you resolved this ? It is still crashing for me. I checked, It has "next" string in my library project. Please guide on resolving this. It is super important.

**Comment by KhanStan99** [comment] 2018-04-09 13:40
@sirajsumra , i removed this library from gradle -> sync -> added again -> sync... resolved

**Closed** 2018-05-16 14:49 UTC

**Comment by Hassanjankhan** [comment] 2019-08-21 11:01
i removed and added again but same problem have you solved it
  Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.prolificinteractive.materialcalendarview.MaterialCalendarView
     Caused by: java.lang.reflect.InvocationTargetExceptionr

**Comment by milanmaji** [comment] 2021-04-23 06:49
Your application base theme should be Material Theme.
Ex: 
<style name ="AppTheme" parent= "Theme.MaterialComponents.Daynight.DarkActionBar" >
...
...
..
</style>
