### ISSUE TITLE
calender not working some time due to follwing issue

### ISSUE THREAD

**Issue by rajscet** [prolificinteractive/material-calendarview#640] opened 2017-08-21 06:15 UTC
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.prolificinteractive.materialcalendarview.DayView.generateRippleDrawable

**Comment by quentin41500** [comment] 2018-05-16 19:30
I would need more information to reproduce, could you get that issue from the sample?

**Comment by quentin41500** [comment] 2018-07-11 17:00
Duplicate of #343

**Closed by quentin41500** 2018-07-11 17:00 UTC
Labels: CNR
