### ISSUE TITLE
Change Font Example

### ISSUE THREAD

**Issue by iad24** [prolificinteractive/material-calendarview#688] opened 2017-11-07 07:45 UTC
I saw thats theres a support for this. But I dont see any example how to change to a custom font.
Anyone can help me?

**Comment by Niroj08** [comment] 2017-12-17 05:41
https://github.com/prolificinteractive/material-calendarview/pull/582

**Comment by quentin41500** [comment] 2018-06-22 16:29
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/688

**Closed by quentin41500** 2018-06-22 16:29 UTC

**Comment by quentin41500** [comment] 2018-06-22 16:31
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/382
